// lib/constants.ts

export const TRACK_OPTIONS = [
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Generative AI",
  "Natural Language Processing",
  "Computer Vision",
  "Robotics",
  "Data Science",
  "Data Analysis",
  "Data Engineering",
  "Big Data Engineering",
  "Business Intelligence",
  "Software Engineering",
  "Backend Development",
  "Frontend Development",
  "Full Stack Development",
  "Mobile App Development",
  "Android Development",
  "iOS Development",
  "Game Development",
  "Web Development",
  "Cloud Computing",
  "DevOps",
  "Site Reliability Engineering",
  "Cybersecurity",
  "Ethical Hacking",
  "Digital Forensics",
  "Network Security",
  "Blockchain Development",
  "Embedded Systems",
  "Internet of Things (IoT)",
  "Operating Systems",
  "Database Administration",
  "Database Engineering",
  "Distributed Systems",
  "Computer Networks",
  "System Programming",
  "Compiler Design",
  "Quantum Computing",
  "Bioinformatics",
  "Human-Computer Interaction",
  "UI/UX Design",
  "AR/VR Development",
  "Product Management",
  "Technical Project Management",
  "IT Support",
  "IT Administration",
  "Automation Engineering",
  "MLOps",
  "AIOps",
];

export const SUGGESTED_SKILLS = [
  "React",
  "Next.js",
  "Python",
  "Machine Learning",
  "Data Analysis",
  "Figma",
  "UI/UX",
  "Node.js",
  "PostgreSQL",
  "Flutter",
  "Java",
  "C++",
  "Cybersecurity",
  "AWS",
  "Docker",
  "Swift",
];
